### ISSUE TITLE
Unable to turn back time after winning or losing the game

### ISSUE THREAD

**Issue by venerablemushroom** [lnRichard/DeepChess#1]
# Unable to turn back time after winning or losing the game.

# Reproduction steps
1. Win the game(or lose if you're a noob)
2. Attempt to reset to a previous turn

# Expected result
Board reverts to an earlier state of the game

# Actual result
Nothing happens

**Comment by lnRichard** [comment]
imagine being so bad

**Comment by lnRichard** [comment]
its a problem with your linux distro, this is what happens to you liberal arch linux users

**Comment by angusyoungnl** [comment]
sudo disable skill issue -gxf --game && sudo enable mode --god

**Comment by lnRichard** [comment]
average linux user

> sudo disable skill issue -gxf --game && sudo enable mode --god

**Comment by lnRichard** [comment]
fix it youself
